spring:
  datasource:
          url: jdbc:mysql://127.0.0.1:3306/world?useSSL=false
          username: root
          password: root
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:com/daimler/itscs/ms/mapper/*.xml
  type-aliases-package: com.daimler.itscs.ms.domain
logging:
  config: classpath:log4j.properties



